In [1]:
import plotly.express as px
import pandas as pd

In [6]:
df = px.data.gapminder().query("country=='Canada'")
df

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

In [7]:
fig = px.line(df, x="year", y="lifeExp")
fig.show()

In [17]:
df = px.data.gapminder().query("continent=='Oceania'")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
60,Australia,Oceania,1952,69.120,8691212,10039.59564,AUS,36
61,Australia,Oceania,1957,70.330,9712569,10949.64959,AUS,36
62,Australia,Oceania,1962,70.930,10794968,12217.22686,AUS,36
63,Australia,Oceania,1967,71.100,11872264,14526.12465,AUS,36
64,Australia,Oceania,1972,71.930,13177000,16788.62948,AUS,36
65,Australia,Oceania,1977,73.490,14074100,18334.19751,AUS,36
66,Australia,Oceania,1982,74.740,15184200,19477.00928,AUS,36
67,Australia,Oceania,1987,76.320,16257249,21888.88903,AUS,36
68,Australia,Oceania,1992,77.560,17481977,23424.76683,AUS,36
69,Australia,Oceania,1997,78.830,18565243,26997.93657,AUS,36
70,Australia,Oceania,2002,80.370,19546792,30687.75473,AUS,36
71,Australia,Oceania,2007,81.235,20434176,34435.36744,AUS,36
1092,New Zealand,Oceania,1952,69.390,1994794,10556.57566,NZL,554
1093,New Zealand,Oceania,1957,70.260,2229407,12247.39532,NZL,554
1094,New Zealand,Oceania,1962,71.240,2488550,13175.67800,NZL,554
1095,New Zealand,Oceania,1967,71.520,2728150,14463.91893,NZL,554
1096,New Zealand,Oceania,1972,71.890,2929100,16046.03728,NZL,554
1097,New Zealand,Oceania,1977,72.220,3164900,16233.71770,NZL,554
1098,New Zealand,Oceania,1982,73.840,3210650,17632.41040,NZL,554
1099,New Zealand,Oceania,1987,74.320,3317166,19007.19129,NZL,554
1100,New Zealand,Oceania,1992,76.330,3437674,18363.32494,NZL,554
1101,New Zealand,Oceania,1997,77.550,3676187,21050.41377,NZL,554
1102,New Zealand,Oceania,2002,79.110,3908037,23189.80135,NZL,554
1103,New Zealand,Oceania,2007,80.204,4115771,25185.00911,NZL,554

In [41]:
fig = px.line(df, x="year", y="lifeExp", color="country", color_discrete_sequence=["pink", "blue"])
fig = px.line(df, 
              x="year", 
              y="lifeExp", 
              color="country", 
              color_discrete_map={"Australia": "#FE41D3", "New Zealand": "#432D4F"},
              markers=True,
              text="lifeExp",
              line_dash="country",
              title="Life Expectency of Oceania people",
              width=800
            )
fig.show()

## BAR CHART

In [43]:
data_thai = px.data.gapminder().query("country=='Thailand'")
data_thai

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
1524,Thailand,Asia,1952,50.848,21289402,757.797418,THA,764
1525,Thailand,Asia,1957,53.630,25041917,793.577415,THA,764
1526,Thailand,Asia,1962,56.061,29263397,1002.199172,THA,764
1527,Thailand,Asia,1967,58.285,34024249,1295.460660,THA,764
1528,Thailand,Asia,1972,60.405,39276153,1524.358936,THA,764
1529,Thailand,Asia,1977,62.494,44148285,1961.224635,THA,764
1530,Thailand,Asia,1982,64.597,48827160,2393.219781,THA,764
1531,Thailand,Asia,1987,66.084,52910342,2982.653773,THA,764
1532,Thailand,Asia,1992,67.298,56667095,4616.896545,THA,764
1533,Thailand,Asia,1997,67.521,60216677,5852.625497,THA,764
1534,Thailand,Asia,2002,68.564,62806748,5913.187529,THA,764
1535,Thailand,Asia,2007,70.616,65068149,7458.396327,THA,764

In [47]:
fig = px.bar(data_thai, x="year", y="pop", color="lifeExp", labels={"pop": "Population", "lifeExp": "Life Expectency"})
fig.show()

In [48]:
data_tha_vie = px.data.gapminder().query("country=='Thailand' or country == 'Vietnam'")
data_tha_vie

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
1524,Thailand,Asia,1952,50.848,21289402,757.797418,THA,764
1525,Thailand,Asia,1957,53.630,25041917,793.577415,THA,764
1526,Thailand,Asia,1962,56.061,29263397,1002.199172,THA,764
1527,Thailand,Asia,1967,58.285,34024249,1295.460660,THA,764
1528,Thailand,Asia,1972,60.405,39276153,1524.358936,THA,764
1529,Thailand,Asia,1977,62.494,44148285,1961.224635,THA,764
1530,Thailand,Asia,1982,64.597,48827160,2393.219781,THA,764
1531,Thailand,Asia,1987,66.084,52910342,2982.653773,THA,764
1532,Thailand,Asia,1992,67.298,56667095,4616.896545,THA,764
1533,Thailand,Asia,1997,67.521,60216677,5852.625497,THA,764
1534,Thailand,Asia,2002,68.564,62806748,5913.187529,THA,764
1535,Thailand,Asia,2007,70.616,65068149,7458.396327,THA,764
1644,Vietnam,Asia,1952,40.412,26246839,605.066492,VNM,704
1645,Vietnam,Asia,1957,42.887,28998543,676.285448,VNM,704
1646,Vietnam,Asia,1962,45.363,33796140,772.049160,VNM,704
1647,Vietnam,Asia,1967,47.838,39463910,637.123289,VNM,704
1648,Vietnam,Asia,1972,50.254,44655014,699.501644,VNM,704
1649,Vietnam,Asia,1977,55.764,50533506,713.537120,VNM,704
1650,Vietnam,Asia,1982,58.816,56142181,707.235786,VNM,704
1651,Vietnam,Asia,1987,62.820,62826491,820.799445,VNM,704
1652,Vietnam,Asia,1992,67.662,69940728,989.023149,VNM,704
1653,Vietnam,Asia,1997,70.672,76048996,1385.896769,VNM,704
1654,Vietnam,Asia,2002,73.017,80908147,1764.456677,VNM,704
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704

In [51]:
fig = px.bar(data_tha_vie, x="year", y="pop", color="country", barmode="group", text="gdpPercap", text_auto=".3s")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside")
fig.show()

## PIE CHARTS

In [61]:
data_asia = px.data.gapminder().query("continent == 'Asia' and year == 2007")
data_asia.loc[data_asia["pop"] < 2 * 10 ** 7, 'country'] = 'Other countries'

In [62]:
fig = px.bar(data_asia, x="year", y="pop", color="country", barmode="group", text="gdpPercap", text_auto=".3s")
fig.update_traces(textfont_size=12, textangle=0, textposition="outside")
fig.show()

In [65]:
fig = px.pie(data_asia, values="pop", names="country", color_discrete_sequence=px.colors.sequential.RdBu)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()